# roles/load/handlers/main.yml
---

- name: restart haproxy
  service:
    name: haproxy
    state: restarted    
    enabled: yes

- name: restart firewalld
  systemd:
    name: firewalld
    state: reloaded

- name: start haproxy
  service:
    name: haproxy
    state: started
    enabled: yes