---
- name: Install Cockpit
  package:
    name:
     - cockpit
     - cockpit-dashboard
- name: Ensure Cockpit is running
  service:
    name: cockpit.socket
    state: started
    enabled: true
    
- name: Allow traffic to Cockpit dashboard through the firewall
  firewalld:
    port: 9090/tcp
    state: enabled
    permanent: true

- name: Insert configuration for remote monitoring
  template: 
    dest: /etc/cockpit/machines.d/
    src: 05-mymachine.json