# group_vars/all.yml
# Variables visible to all nodes
---
mariadb_databases: 
  - name: wordpress
mariadb_users: 
  - name: wordpress #required; the rest are optional
    password: wordpress
    priv: 'wordpress.*:ALL'
    host: 192.168.56.%

mariadb_bind_address: '0.0.0.0'

wordpress_database_host: 192.168.56.9
wordpress_database: wordpress
wordpress_user: wordpress
wordpress_password: wordpress
mariadb_root_password: 'wordpress'

httpd_listen: 8080

wordpress_plugins: 
  - name: varnish-http-purge
    version: 4.8.1

rhbase_firewall_allow_services: 
  - http
  - https
rhbase_firewall_allow_ports: []